"""Initial migration

Revision ID: 4dd853efe512
Revises: c28a940ed93b
Create Date: 2025-08-05 13:45:35.468788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dd853efe512'
down_revision = 'c28a940ed93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spotify_id')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('track_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('track_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('artist_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_rating_timestamp'))
        batch_op.drop_index(batch_op.f('ix_rating_track_id'))
        batch_op.drop_index(batch_op.f('ix_rating_user_id'))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('review')
        batch_op.drop_column('rating_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_value', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('review', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_rating_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_track_id'), ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_timestamp'), ['timestamp'], unique=False)
        batch_op.alter_column('artist_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               nullable=True)
        batch_op.alter_column('track_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               nullable=True)
        batch_op.alter_column('track_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
        batch_op.drop_column('rating')

    op.drop_table('user')
    # ### end Alembic commands ###
