"""Adiciona colunas para nome da musica e artista

Revision ID: c28a940ed93b
Revises: 
Create Date: 2025-08-05 11:00:36.803648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c28a940ed93b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('artist_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('rating_value', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('track_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_rating_track_id'), ['track_id'], unique=False)
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', mysql.FLOAT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_rating_track_id'))
        batch_op.alter_column('track_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               existing_nullable=True)
        batch_op.drop_column('rating_value')
        batch_op.drop_column('artist_name')
        batch_op.drop_column('track_name')

    # ### end Alembic commands ###
